### ISSUE TITLE
Discord Bot Active API Downtime Alerts

### ISSUE THREAD

**Issue by Ferrariic** [Bot-detector/bot-detector-discord-bot#108]
We could have the discord bot ping the API every 5 minutes, and alert us once, with an exponential step off, when the API is down.

**Comment by extreme4all** [comment]
ideally this should come from our logging, because there can be just one node not responding.

**Comment by Ferrariic** [comment]
Yes that could come from logging, good idea. Then we could use that to evaluate each route actually with a failrate perhaps
